# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f2071ecfc0e90e7027de85feb3350ef2fc1edf717a3d06fd8944d7c1369b2c41466a551e2529cc3eae10a557e7a9f74f28139f924cba3920d23c9b6bb930e20

test:
  secret_key_base: 58b47e7f0e2a19a4658d70033d06e363a24fd2e6d81b14b86c7b2bfc516f8fd7ff35bf8d1236d8bc68db643d33128b2da921bdb26f2b8764aa0899893edc4b9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
